// this code is autogenerated, do not check it into to your code repository

// ref lib/zog/flow.ex:18
const std = @import("std");
const beam = @import("beam");
const zog = @import("zog");

const FlowNifResult = struct {
    max_flow: f64,
    residual_from: []u32,
    residual_to: []u32,
    residual_cap: []f64,
    source_side: []u32,
    sink_side: []u32,
};

fn buildGraph(
    allocator: std.mem.Allocator,
    node_count: usize,
    from: []u32,
    to: []u32,
    capacity: []f64,
) !zog.models.ArrayGraph(void, f64) {
    const ArrayGraph = zog.models.ArrayGraph;
    var g = ArrayGraph(void, f64).init(allocator);
    errdefer g.deinit();

    try g.nodes.ensureTotalCapacity(allocator, node_count);
    try g.edges.ensureTotalCapacity(allocator, from.len);

    for (0..node_count) |_| {
        _ = try g.addNode({});
    }

    for (from, to, capacity) |f, t, w| {
        _ = try g.addEdge(f, t, w);
    }

    return g;
}

fn toFlowNifResult(
    allocator: std.mem.Allocator,
    max_flow: f64,
    residual: anytype,
    source_side: []u32,
    sink_side: []u32,
) !FlowNifResult {
    const res_count = residual.count();
    var res_from = try allocator.alloc(u32, res_count);
    errdefer allocator.free(res_from);
    var res_to = try allocator.alloc(u32, res_count);
    errdefer allocator.free(res_to);
    var res_cap = try allocator.alloc(f64, res_count);
    errdefer allocator.free(res_cap);

    var it = residual.iterator();
    var idx: usize = 0;
    while (it.next()) |entry| {
        res_from[idx] = entry.key_ptr.from;
        res_to[idx] = entry.key_ptr.to;
        res_cap[idx] = entry.value_ptr.*;
        idx += 1;
    }

    const ss = try allocator.alloc(u32, source_side.len);
    errdefer allocator.free(ss);
    @memcpy(ss, source_side);

    const sk = try allocator.alloc(u32, sink_side.len);
    errdefer allocator.free(sk);
    @memcpy(sk, sink_side);

    return .{
        .max_flow = max_flow,
        .residual_from = res_from,
        .residual_to = res_to,
        .residual_cap = res_cap,
        .source_side = ss,
        .sink_side = sk,
    };
}

pub fn edmonds_karp_f64(
    node_count: usize,
    from: []u32,
    to: []u32,
    capacity: []f64,
    source: u32,
    sink: u32,
) !FlowNifResult {
    const allocator = beam.allocator;
    var g = try buildGraph(allocator, node_count, from, to, capacity);
    defer g.deinit();

    var result = try zog.flow.max_flow.edmondsKarpF64(allocator, g, source, sink);
    defer result.deinit(allocator);

    var cut = try zog.flow.max_flow.minCut(allocator, result, f64, 0.0, zog.utils.compareF64);
    defer cut.deinit(allocator);

    return try toFlowNifResult(allocator, result.max_flow, result.residual, cut.source_side, cut.sink_side);
}

pub fn push_relabel_f64(
    node_count: usize,
    from: []u32,
    to: []u32,
    capacity: []f64,
    source: u32,
    sink: u32,
) !FlowNifResult {
    const allocator = beam.allocator;
    var g = try buildGraph(allocator, node_count, from, to, capacity);
    defer g.deinit();

    var result = try zog.flow.max_flow.pushRelabelF64(allocator, g, source, sink);
    defer result.deinit(allocator);

    var cut = try zog.flow.max_flow.minCut(allocator, result, f64, 0.0, zog.utils.compareF64);
    defer cut.deinit(allocator);

    return try toFlowNifResult(allocator, result.max_flow, result.residual, cut.source_side, cut.sink_side);
}

const MinCutNifResult = struct {
    cut_value: f64,
    source_side: []u32,
    sink_side: []u32,
};

pub fn global_min_cut_f64(
    node_count: usize,
    from: []u32,
    to: []u32,
    capacity: []f64,
) !MinCutNifResult {
    const allocator = beam.allocator;
    const ArrayGraph = zog.models.ArrayGraph;

    var g = ArrayGraph(void, f64).init(allocator);
    defer g.deinit();

    try g.nodes.ensureTotalCapacity(allocator, node_count);
    try g.edges.ensureTotalCapacity(allocator, from.len);

    for (0..node_count) |_| {
        _ = try g.addNode({});
    }

    for (from, to, capacity) |f, t, w| {
        _ = try g.addEdge(f, t, w);
    }

    const result = try zog.flow.min_cut.globalMinCutF64(allocator, g);

    return .{
        .cut_value = result.weight,
        .source_side = result.group_a,
        .sink_side = result.group_b,
    };
}
