// this code is autogenerated, do not check it into to your code repository

// ref lib/zog/connectivity.ex:19
const std = @import("std");
const beam = @import("beam");
const zog = @import("zog");

const ArrayGraph = zog.models.ArrayGraph;

fn buildGraph(node_count: usize, from: []u32, to: []u32, weight: []f64) !ArrayGraph(void, f64) {
    const allocator = beam.allocator;
    var g = ArrayGraph(void, f64).init(allocator);
    errdefer g.deinit();

    try g.nodes.ensureTotalCapacity(allocator, node_count);
    try g.edges.ensureTotalCapacity(allocator, from.len);

    for (0..node_count) |_| {
        _ = try g.addNode({});
    }

    for (from, to, weight) |f, t, w| {
        _ = try g.addEdge(f, t, w);
    }

    return g;
}

pub fn nif_core_numbers(node_count: usize, from: []u32, to: []u32, weight: []f64) ![]u32 {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    return try zog.connectivity.coreNumbers(beam.allocator, g);
}

pub fn nif_strongly_connected_components(node_count: usize, from: []u32, to: []u32, weight: []f64) ![]u32 {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    return try zog.connectivity.stronglyConnectedComponents(beam.allocator, g);
}

pub fn nif_weakly_connected_components(node_count: usize, from: []u32, to: []u32, weight: []f64) ![]u32 {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    return try zog.connectivity.weaklyConnectedComponents(beam.allocator, g);
}

pub fn nif_is_bipartite(node_count: usize, from: []u32, to: []u32, weight: []f64) !beam.term {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    const result = try zog.connectivity.isBipartite(beam.allocator, g);
    switch (result) {
        .bipartite => |colors| {
            errdefer beam.allocator.free(colors);
            const term = beam.make(.{ .bipartite, colors }, .{});
            beam.allocator.free(colors);
            return term;
        },
        .not_bipartite => return beam.make(.not_bipartite, .{}),
    }
}

pub fn nif_analyze_connectivity(node_count: usize, from: []u32, to: []u32, weight: []f64) !beam.term {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    const res = try zog.connectivity.analyzeConnectivity(beam.allocator, g);
    errdefer {
        beam.allocator.free(res.bridges);
        beam.allocator.free(res.articulation_points);
    }

    const term = beam.make(.{.ok, res.bridges, res.articulation_points}, .{});

    beam.allocator.free(res.bridges);
    beam.allocator.free(res.articulation_points);

    return term;
}
