// this code is autogenerated, do not check it into to your code repository

// ref lib/zog/health_metrics.ex:22
const std = @import("std");
const beam = @import("beam");
const zog = @import("zog");

const ArrayGraph = zog.models.ArrayGraph;

fn buildGraph(node_count: usize, from: []u32, to: []u32, weight: []f64) !ArrayGraph(void, f64) {
    const allocator = beam.allocator;
    var g = ArrayGraph(void, f64).init(allocator);
    errdefer g.deinit();

    try g.nodes.ensureTotalCapacity(allocator, node_count);
    try g.edges.ensureTotalCapacity(allocator, from.len);

    for (0..node_count) |_| {
        _ = try g.addNode({});
    }

    for (from, to, weight) |f, t, w| {
        _ = try g.addEdge(f, t, w);
    }

    return g;
}

pub fn nif_health_metrics(node_count: usize, from: []u32, to: []u32, weight: []f64) !beam.term {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    var result = try zog.health_metrics.analyze(beam.allocator, g);
    defer result.deinit(beam.allocator);

    return beam.make(.{
        .ok,
        result.eccentricity,
        result.diameter,
        result.radius,
        result.average_path_length,
    }, .{});
}
