// this code is autogenerated, do not check it into to your code repository

// ref lib/zog/resource_graph.ex:51
const std = @import("std");
const beam = @import("beam");
const e = @import("erl_nif");
const zog = @import("zog");
const ArrayGraph = zog.models.ArrayGraph;

const GraphResource = struct {
    graph: ArrayGraph(void, f64),
};

pub const GraphRes = beam.Resource(GraphResource, @import("root"), .{
    .Callbacks = struct {
        pub fn dtor(ptr: *GraphResource) void {
            ptr.graph.deinit();
        }
    },
});

fn buildGraph(node_count: usize, from: []u32, to: []u32, weight: []f64) !ArrayGraph(void, f64) {
    const allocator = beam.allocator;
    var g = ArrayGraph(void, f64).init(allocator);
    errdefer g.deinit();
    try g.nodes.ensureTotalCapacity(allocator, node_count);
    try g.edges.ensureTotalCapacity(allocator, from.len);
    for (0..node_count) |_| { _ = try g.addNode({}); }
    for (from, to, weight) |f, t, w| { _ = try g.addEdge(f, t, w); }
    return g;
}

fn extractScores(result: anytype, node_count: usize) ![]f64 {
    const allocator = beam.allocator;
    var scores = try allocator.alloc(f64, node_count);
    errdefer allocator.free(scores);
    for (0..node_count) |i| {
        scores[i] = result.get(@intCast(i));
    }
    return scores;
}

fn extractAssignments(result: anytype, node_count: usize) ![]usize {
    const allocator = beam.allocator;
    var assignments = try allocator.alloc(usize, node_count);
    errdefer allocator.free(assignments);
    for (0..node_count) |i| {
        assignments[i] = result.assignments.get(@intCast(i)) orelse 0;
    }
    return assignments;
}

pub fn new(node_count: usize, from: []u32, to: []u32, weight: []f64) !GraphRes {
    const g = try buildGraph(node_count, from, to, weight);
    return GraphRes.create(.{ .graph = g }, .{ .released = false });
}

pub fn nif_destroy(res: GraphRes) void {
    res.release();
}

pub fn nif_betweenness_unweighted(res: GraphRes) ![]f64 {
    const g = res.unpack().graph;
    var result = try zog.centrality.betweennessUnweighted(beam.allocator, g);
    defer result.deinit();
    return extractScores(result, g.nodeCapacity());
}

pub fn nif_betweenness_f64(res: GraphRes) ![]f64 {
    const g = res.unpack().graph;
    var result = try zog.centrality.betweennessF64(beam.allocator, g);
    defer result.deinit();
    return extractScores(result, g.nodeCapacity());
}

pub fn nif_closeness_f64(res: GraphRes) ![]f64 {
    const g = res.unpack().graph;
    var result = try zog.centrality.closenessF64(beam.allocator, g);
    defer result.deinit();
    return extractScores(result, g.nodeCapacity());
}

pub fn nif_harmonic_centrality_f64(res: GraphRes) ![]f64 {
    const g = res.unpack().graph;
    var result = try zog.centrality.harmonicCentralityF64(beam.allocator, g);
    defer result.deinit();
    return extractScores(result, g.nodeCapacity());
}

pub fn pagerank(res: GraphRes, damping: f64, max_iterations: usize, tolerance: f64) ![]f64 {
    const g = res.unpack().graph;
    var result = try zog.centrality.pagerank(beam.allocator, g, .{
        .damping = damping,
        .max_iterations = max_iterations,
        .tolerance = tolerance,
    });
    defer result.deinit();
    return extractScores(result, g.nodeCapacity());
}

pub fn eigenvector(res: GraphRes, max_iterations: usize, tolerance: f64) ![]f64 {
    const g = res.unpack().graph;
    var result = try zog.centrality.eigenvector(beam.allocator, g, max_iterations, tolerance);
    defer result.deinit();
    return extractScores(result, g.nodeCapacity());
}

pub fn katz(res: GraphRes, alpha: f64, beta: f64, max_iterations: usize, tolerance: f64) ![]f64 {
    const g = res.unpack().graph;
    var result = try zog.centrality.katz(beam.allocator, g, alpha, beta, max_iterations, tolerance);
    defer result.deinit();
    return extractScores(result, g.nodeCapacity());
}

pub fn alpha_centrality(res: GraphRes, alpha: f64, initial: f64, max_iterations: usize, tolerance: f64) ![]f64 {
    const g = res.unpack().graph;
    var result = try zog.centrality.alphaCentrality(beam.allocator, g, alpha, initial, max_iterations, tolerance);
    defer result.deinit();
    return extractScores(result, g.nodeCapacity());
}

pub fn louvain(res: GraphRes, min_modularity_gain: f64, max_iterations: usize, seed: u64) ![]usize {
    const g = res.unpack().graph;
    var result = try zog.community.louvain.detectWeightedWithOptions(
        beam.allocator,
        g,
        .{
            .min_modularity_gain = min_modularity_gain,
            .max_iterations = max_iterations,
            .seed = seed,
        },
        zog.utils.identityF64,
    );
    defer result.deinit();
    return extractAssignments(result, g.nodeCapacity());
}

pub fn leiden(
    res: GraphRes,
    min_modularity_gain: f64,
    max_iterations: usize,
    seed: u64,
    theta: f64,
) ![]usize {
    const g = res.unpack().graph;
    var result = try zog.community.leiden.detectWeightedWithOptions(
        beam.allocator,
        g,
        .{
            .min_modularity_gain = min_modularity_gain,
            .max_iterations = max_iterations,
            .seed = seed,
            .theta = theta,
        },
        zog.utils.identityF64,
    );
    defer result.deinit();
    return extractAssignments(result, g.nodeCapacity());
}

pub fn leiden_hierarchical(
    res: GraphRes,
    min_modularity_gain: f64,
    max_iterations: usize,
    seed: u64,
    theta: f64,
) ![][]usize {
    const g = res.unpack().graph;
    var result = try zog.community.leiden.detectHierarchicalWeightedWithOptions(
        beam.allocator,
        g,
        .{
            .min_modularity_gain = min_modularity_gain,
            .max_iterations = max_iterations,
            .seed = seed,
            .theta = theta,
        },
        zog.utils.identityF64,
    );
    defer result.deinit();

    const allocator = beam.allocator;
    const node_count = g.nodeCapacity();
    const outer = try allocator.alloc([]usize, result.levels.len);
    errdefer allocator.free(outer);

    for (result.levels, 0..) |level, i| {
        const level_copy = try allocator.alloc(usize, node_count);
        errdefer allocator.free(level_copy);
        @memcpy(level_copy, level);
        outer[i] = level_copy;
    }

    return outer;
}

pub fn modularity_f64(res: GraphRes, assignments: []usize) !f64 {
    const g = res.unpack().graph;
    var map = std.AutoHashMap(u32, usize).init(beam.allocator);
    defer map.deinit();
    for (assignments, 0..) |comm, i| {
        try map.put(@intCast(i), comm);
    }
    return try zog.community.metrics.modularity(beam.allocator, g, map, zog.utils.identityF64);
}

fn extractMatrix(result: anytype, node_count: usize) !beam.term {
    var matrix = try beam.allocator.alloc(f64, node_count * node_count);
    defer beam.allocator.free(matrix);
    for (0..node_count) |i| {
        for (0..node_count) |j| {
            matrix[i * node_count + j] = result.get(@intCast(i), @intCast(j)) orelse std.math.inf(f64);
        }
    }
    return beam.make(.{.ok, matrix}, .{});
}

pub fn nif_floyd_warshall(res: GraphRes) !beam.term {
    const g = res.unpack().graph;
    const node_count = g.nodeCapacity();
    var result = zog.pathfinding.floydWarshall(beam.allocator, g) catch |err| {
        if (err == error.NegativeCycle) {
            return beam.make(.{.@"error", .negative_cycle}, .{});
        }
        return err;
    };
    defer result.deinit();
    return extractMatrix(result, node_count);
}

pub fn nif_johnsons(res: GraphRes) !beam.term {
    const g = res.unpack().graph;
    const node_count = g.nodeCapacity();
    var result = zog.pathfinding.johnsonsGeneric(
        beam.allocator, g, f64, 0.0,
        zog.utils.addF64, zog.utils.subF64, zog.utils.compareF64,
    ) catch |err| {
        if (err == error.NegativeCycle) {
            return beam.make(.{.@"error", .negative_cycle}, .{});
        }
        return err;
    };
    defer result.deinit();
    return extractMatrix(result, node_count);
}

pub fn nif_dijkstra(res: GraphRes, start_node: u32, goal_node: u32) !beam.term {
    const g = res.unpack().graph;
    const opt_res = zog.pathfinding.dijkstra(beam.allocator, g, start_node, goal_node) catch |err| {
        return err;
    };

    if (opt_res) |res_val| {
        var path_res = res_val;
        defer path_res.deinit(beam.allocator);

        const path_slice = try beam.allocator.alloc(u32, path_res.path.items.len);
        @memcpy(path_slice, path_res.path.items);

        return beam.make(.{.ok, .{path_slice, path_res.weight}}, .{});
    } else {
        return beam.make(.{.@"error", .no_path}, .{});
    }
}

pub fn nif_density(res: GraphRes) !f64 {
    const g = res.unpack().graph;
    const n = g.nodeCount();
    if (n <= 1) return 0.0;
    const possible_edges = @as(f64, @floatFromInt(n * (n - 1)));
    return @as(f64, @floatFromInt(g.edgeCount())) / possible_edges;
}

pub fn nif_triangle_count(res: GraphRes) !usize {
    const g = res.unpack().graph;
    return try zog.community.metrics.countTriangles(beam.allocator, g);
}

pub fn nif_average_clustering_coefficient(res: GraphRes) !f64 {
    const g = res.unpack().graph;
    return try zog.community.metrics.averageClusteringCoefficient(beam.allocator, g);
}

pub fn nif_local_clustering_coefficient(res: GraphRes) ![]f64 {
    const g = res.unpack().graph;
    const node_count = g.nodeCapacity();
    var scores = try beam.allocator.alloc(f64, node_count);
    errdefer beam.allocator.free(scores);
    for (0..node_count) |i| {
        scores[i] = zog.community.metrics.clusteringCoefficient(beam.allocator, g, @intCast(i)) catch 0.0;
    }
    return scores;
}

pub fn nif_assortativity(res: GraphRes) !f64 {
    const g = res.unpack().graph;
    return try zog.metrics.assortativity(beam.allocator, g);
}

pub fn nif_core_numbers(res: GraphRes) ![]u32 {
    const g = res.unpack().graph;
    return try zog.connectivity.coreNumbers(beam.allocator, g);
}

pub fn nif_analyze_connectivity(res: GraphRes) !beam.term {
    const g = res.unpack().graph;
    const res_conn = try zog.connectivity.analyzeConnectivity(beam.allocator, g);
    errdefer {
        beam.allocator.free(res_conn.bridges);
        beam.allocator.free(res_conn.articulation_points);
    }

    const term = beam.make(.{.ok, res_conn.bridges, res_conn.articulation_points}, .{});

    beam.allocator.free(res_conn.bridges);
    beam.allocator.free(res_conn.articulation_points);

    return term;
}

const FlowNifResult = struct {
    max_flow: f64,
    residual_from: []u32,
    residual_to: []u32,
    residual_cap: []f64,
    source_side: []u32,
    sink_side: []u32,
};

fn toFlowNifResult(
    allocator: std.mem.Allocator,
    max_flow: f64,
    residual: anytype,
    source_side: []u32,
    sink_side: []u32,
) !FlowNifResult {
    const res_count = residual.count();
    var res_from = try allocator.alloc(u32, res_count);
    errdefer allocator.free(res_from);
    var res_to = try allocator.alloc(u32, res_count);
    errdefer allocator.free(res_to);
    var res_cap = try allocator.alloc(f64, res_count);
    errdefer allocator.free(res_cap);

    var it = residual.iterator();
    var idx: usize = 0;
    while (it.next()) |entry| {
        res_from[idx] = entry.key_ptr.from;
        res_to[idx] = entry.key_ptr.to;
        res_cap[idx] = entry.value_ptr.*;
        idx += 1;
    }

    const ss = try allocator.alloc(u32, source_side.len);
    errdefer allocator.free(ss);
    @memcpy(ss, source_side);

    const sk = try allocator.alloc(u32, sink_side.len);
    errdefer allocator.free(sk);
    @memcpy(sk, sink_side);

    return .{
        .max_flow = max_flow,
        .residual_from = res_from,
        .residual_to = res_to,
        .residual_cap = res_cap,
        .source_side = ss,
        .sink_side = sk,
    };
}

pub fn nif_max_flow(res: GraphRes, source: u32, sink: u32) !FlowNifResult {
    const allocator = beam.allocator;
    const g = res.unpack().graph;

    var result = try zog.flow.max_flow.edmondsKarpF64(allocator, g, source, sink);
    defer result.deinit(allocator);

    var cut = try zog.flow.max_flow.minCut(allocator, result, f64, 0.0, zog.utils.compareF64);
    defer cut.deinit(allocator);

    return try toFlowNifResult(allocator, result.max_flow, result.residual, cut.source_side, cut.sink_side);
}

pub fn nif_push_relabel(res: GraphRes, source: u32, sink: u32) !FlowNifResult {
    const allocator = beam.allocator;
    const g = res.unpack().graph;

    var result = try zog.flow.max_flow.pushRelabelF64(allocator, g, source, sink);
    defer result.deinit(allocator);

    var cut = try zog.flow.max_flow.minCut(allocator, result, f64, 0.0, zog.utils.compareF64);
    defer cut.deinit(allocator);

    return try toFlowNifResult(allocator, result.max_flow, result.residual, cut.source_side, cut.sink_side);
}

const MinCutNifResult = struct {
    cut_value: f64,
    source_side: []u32,
    sink_side: []u32,
};

pub fn nif_global_min_cut(res: GraphRes) !MinCutNifResult {
    const allocator = beam.allocator;
    const g = res.unpack().graph;

    const result = try zog.flow.min_cut.globalMinCutF64(allocator, g);

    return .{
        .cut_value = result.weight,
        .source_side = result.group_a,
        .sink_side = result.group_b,
    };
}

fn getOrInsertNode(
    arena: std.mem.Allocator,
    g: *ArrayGraph(void, f64),
    label_to_id: *std.StringHashMap(u32),
    labels_list: *std.ArrayList([]const u8),
    next_id: *u32,
    label: []const u8,
) !u32 {
    if (label_to_id.get(label)) |id| {
        return id;
    }
    const id = next_id.*;
    _ = try g.addNode({});
    const key_copy = try arena.dupe(u8, label);
    try label_to_id.put(key_copy, id);
    try labels_list.append(arena, key_copy);
    next_id.* += 1;
    return id;
}

pub fn nif_read_edgelist(file_path: []const u8, is_directed: bool) !beam.term {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const arena_allocator = arena.allocator();

    var file = try std.fs.cwd().openFile(file_path, .{});
    defer file.close();

    var g = ArrayGraph(void, f64).init(beam.allocator);
    errdefer g.deinit();

    var label_to_id = std.StringHashMap(u32).init(arena_allocator);
    var labels_list: std.ArrayList([]const u8) = .empty;
    defer labels_list.deinit(arena_allocator);
    var next_id: u32 = 0;

    var read_buffer: [4096]u8 = undefined;
    var file_reader = file.reader(&read_buffer);
    const reader = &file_reader.interface;

    while (true) {
        const line = reader.takeDelimiterExclusive('\n') catch |err| {
            if (err == error.EndOfStream) break;
            return err;
        };
        reader.toss(1);

        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (trimmed.len == 0 or trimmed[0] == '#') continue;

        var parts = std.mem.tokenizeAny(u8, trimmed, " \t,");
        const src_lbl = parts.next() orelse continue;
        const dst_lbl = parts.next() orelse continue;
        const opt_weight = parts.next();

        const weight = if (opt_weight) |w_str| std.fmt.parseFloat(f64, w_str) catch 1.0 else 1.0;

        const src_id = try getOrInsertNode(arena_allocator, &g, &label_to_id, &labels_list, &next_id, src_lbl);
        const dst_id = try getOrInsertNode(arena_allocator, &g, &label_to_id, &labels_list, &next_id, dst_lbl);

        _ = try g.addEdge(src_id, dst_id, weight);
        if (!is_directed) {
            _ = try g.addEdge(dst_id, src_id, weight);
        }
    }

    const resource = try GraphRes.create(.{ .graph = g }, .{ .released = false });
    const labels_slice = try labels_list.toOwnedSlice(arena_allocator);
    return beam.make(.{.ok, resource, labels_slice}, .{});
}

pub fn nif_read_adjlist(file_path: []const u8, is_directed: bool) !beam.term {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const arena_allocator = arena.allocator();

    var file = try std.fs.cwd().openFile(file_path, .{});
    defer file.close();

    var g = ArrayGraph(void, f64).init(beam.allocator);
    errdefer g.deinit();

    var label_to_id = std.StringHashMap(u32).init(arena_allocator);
    var labels_list: std.ArrayList([]const u8) = .empty;
    defer labels_list.deinit(arena_allocator);
    var next_id: u32 = 0;

    var read_buffer: [4096]u8 = undefined;
    var file_reader = file.reader(&read_buffer);
    const reader = &file_reader.interface;

    while (true) {
        const line = reader.takeDelimiterExclusive('\n') catch |err| {
            if (err == error.EndOfStream) break;
            return err;
        };
        reader.toss(1);

        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (trimmed.len == 0 or trimmed[0] == '#') continue;

        const colon_idx = std.mem.indexOf(u8, trimmed, ":") orelse continue;
        const src_lbl = std.mem.trim(u8, trimmed[0..colon_idx], " \t");
        const neighbors_part = trimmed[colon_idx + 1 ..];

        const src_id = try getOrInsertNode(arena_allocator, &g, &label_to_id, &labels_list, &next_id, src_lbl);

        var neighbors_it = std.mem.tokenizeAny(u8, neighbors_part, " \t");
        while (neighbors_it.next()) |neighbor_token| {
            var neighbor_parts = std.mem.splitScalar(u8, neighbor_token, ',');
            const dst_lbl = neighbor_parts.first();
            const opt_w = neighbor_parts.next();
            const weight = if (opt_w) |w_str| std.fmt.parseFloat(f64, w_str) catch 1.0 else 1.0;

            const dst_id = try getOrInsertNode(arena_allocator, &g, &label_to_id, &labels_list, &next_id, dst_lbl);
            _ = try g.addEdge(src_id, dst_id, weight);
            if (!is_directed) {
                _ = try g.addEdge(dst_id, src_id, weight);
            }
        }
    }

    const resource = try GraphRes.create(.{ .graph = g }, .{ .released = false });
    const labels_slice = try labels_list.toOwnedSlice(arena_allocator);
    return beam.make(.{.ok, resource, labels_slice}, .{});
}

pub fn nif_read_tgf(file_path: []const u8, is_directed: bool) !beam.term {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const arena_allocator = arena.allocator();

    var file = try std.fs.cwd().openFile(file_path, .{});
    defer file.close();

    var g = ArrayGraph(void, f64).init(beam.allocator);
    errdefer g.deinit();

    var label_to_id = std.StringHashMap(u32).init(arena_allocator);
    var labels_list: std.ArrayList([]const u8) = .empty;
    defer labels_list.deinit(arena_allocator);
    var next_id: u32 = 0;

    var parsing_edges = false;
    var read_buffer: [4096]u8 = undefined;
    var file_reader = file.reader(&read_buffer);
    const reader = &file_reader.interface;

    while (true) {
        const line = reader.takeDelimiterExclusive('\n') catch |err| {
            if (err == error.EndOfStream) break;
            return err;
        };
        reader.toss(1);

        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (trimmed.len == 0) continue;

        if (std.mem.eql(u8, trimmed, "#")) {
            parsing_edges = true;
            continue;
        }

        if (!parsing_edges) {
            var parts = std.mem.tokenizeAny(u8, trimmed, " \t");
            const node_lbl = parts.next() orelse continue;
            _ = try getOrInsertNode(arena_allocator, &g, &label_to_id, &labels_list, &next_id, node_lbl);
        } else {
            var parts = std.mem.tokenizeAny(u8, trimmed, " \t");
            const src_lbl = parts.next() orelse continue;
            const dst_lbl = parts.next() orelse continue;
            const opt_w = parts.next();
            const weight = if (opt_w) |w_str| std.fmt.parseFloat(f64, w_str) catch 1.0 else 1.0;

            const src_id = try getOrInsertNode(arena_allocator, &g, &label_to_id, &labels_list, &next_id, src_lbl);
            const dst_id = try getOrInsertNode(arena_allocator, &g, &label_to_id, &labels_list, &next_id, dst_lbl);

            _ = try g.addEdge(src_id, dst_id, weight);
            if (!is_directed) {
                _ = try g.addEdge(dst_id, src_id, weight);
            }
        }
    }

    const resource = try GraphRes.create(.{ .graph = g }, .{ .released = false });
    const labels_slice = try labels_list.toOwnedSlice(arena_allocator);
    return beam.make(.{.ok, resource, labels_slice}, .{});
}
