// this code is autogenerated, do not check it into to your code repository

// ref lib/zog/pathfinding.ex:20
const std = @import("std");
const beam = @import("beam");
const zog = @import("zog");

const ArrayGraph = zog.models.ArrayGraph;

fn buildGraph(node_count: usize, from: []u32, to: []u32, weight: []f64) !ArrayGraph(void, f64) {
    const allocator = beam.allocator;
    var g = ArrayGraph(void, f64).init(allocator);
    errdefer g.deinit();

    try g.nodes.ensureTotalCapacity(allocator, node_count);
    try g.edges.ensureTotalCapacity(allocator, from.len);

    for (0..node_count) |_| {
        _ = try g.addNode({});
    }

    for (from, to, weight) |f, t, w| {
        _ = try g.addEdge(f, t, w);
    }

    return g;
}

fn extractMatrix(result: anytype, node_count: usize) !beam.term {
    const allocator = beam.allocator;
    var matrix = try allocator.alloc(f64, node_count * node_count);
    defer allocator.free(matrix);

    for (0..node_count) |i| {
        for (0..node_count) |j| {
            const val = result.get(@intCast(i), @intCast(j));
            matrix[i * node_count + j] = val orelse std.math.inf(f64);
        }
    }

    return beam.make(.{.ok, matrix}, .{});
}

pub fn floyd_warshall(node_count: usize, from: []u32, to: []u32, weight: []f64) !beam.term {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    var result = zog.pathfinding.floydWarshall(beam.allocator, g) catch |err| {
        if (err == error.NegativeCycle) {
            return beam.make(.{.@"error", .negative_cycle}, .{});
        }
        return err;
    };
    defer result.deinit();

    return extractMatrix(result, node_count);
}

pub fn johnsons(node_count: usize, from: []u32, to: []u32, weight: []f64) !beam.term {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    var result = zog.pathfinding.johnsonsGeneric(
        beam.allocator,
        g,
        f64,
        0.0,
        zog.utils.addF64,
        zog.utils.subF64,
        zog.utils.compareF64,
    ) catch |err| {
        if (err == error.NegativeCycle) {
            return beam.make(.{.@"error", .negative_cycle}, .{});
        }
        return err;
    };
    defer result.deinit();

    return extractMatrix(result, node_count);
}

pub fn nif_dijkstra(
    node_count: usize,
    from: []u32,
    to: []u32,
    weight: []f64,
    start_node: u32,
    goal_node: u32,
) !beam.term {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    const opt_res = zog.pathfinding.dijkstra(beam.allocator, g, start_node, goal_node) catch |err| {
        return err;
    };

    if (opt_res) |res| {
        var path_res = res;
        defer path_res.deinit(beam.allocator);

        const path_slice = try beam.allocator.alloc(u32, path_res.path.items.len);
        @memcpy(path_slice, path_res.path.items);

        return beam.make(.{.ok, .{path_slice, path_res.weight}}, .{});
    } else {
        return beam.make(.{.@"error", .no_path}, .{});
    }
}

pub fn nif_bellman_ford(
    node_count: usize,
    from: []u32,
    to: []u32,
    weight: []f64,
    start_node: u32,
    goal_node: u32,
) !beam.term {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    const opt_res = zog.pathfinding.bellmanFord(beam.allocator, g, start_node, goal_node) catch |err| {
        if (err == error.NegativeCycle) {
            return beam.make(.{.@"error", .negative_cycle}, .{});
        }
        return err;
    };

    if (opt_res) |res| {
        var path_res = res;
        defer path_res.deinit(beam.allocator);

        const path_slice = try beam.allocator.alloc(u32, path_res.path.items.len);
        @memcpy(path_slice, path_res.path.items);

        return beam.make(.{.ok, .{path_slice, path_res.weight}}, .{});
    } else {
        return beam.make(.{.@"error", .no_path}, .{});
    }
}

pub fn nif_astar(
    node_count: usize,
    from: []u32,
    to: []u32,
    weight: []f64,
    start_node: u32,
    goal_node: u32,
    x_coords: []f64,
    y_coords: []f64,
    heuristic: beam.term,
) !beam.term {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    const HeuristicType = zog.pathfinding.HeuristicType;
    const h_type = try beam.get(HeuristicType, heuristic, .{});

    const opt_res = zog.pathfinding.astar(beam.allocator, g, start_node, goal_node, x_coords, y_coords, h_type) catch |err| {
        return err;
    };

    if (opt_res) |res| {
        var path_res = res;
        defer path_res.deinit(beam.allocator);

        const path_slice = try beam.allocator.alloc(u32, path_res.path.items.len);
        @memcpy(path_slice, path_res.path.items);

        return beam.make(.{.ok, .{path_slice, path_res.weight}}, .{});
    } else {
        return beam.make(.{.@"error", .no_path}, .{});
    }
}

pub fn nif_is_reachable(
    node_count: usize,
    from: []u32,
    to: []u32,
    weight: []f64,
    start_node: u32,
    goal_node: u32,
) !beam.term {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    const reachable = try zog.pathfinding.isReachable(beam.allocator, g, start_node, goal_node);
    return beam.make(reachable, .{});
}
