// this code is autogenerated, do not check it into to your code repository

// ref lib/zog/centrality.ex:24
const std = @import("std");
const beam = @import("beam");
const zog = @import("zog");

const ArrayGraph = zog.models.ArrayGraph;

fn buildGraph(node_count: usize, from: []u32, to: []u32, weight: []f64) !ArrayGraph(void, f64) {
    const allocator = beam.allocator;
    var g = ArrayGraph(void, f64).init(allocator);
    errdefer g.deinit();

    try g.nodes.ensureTotalCapacity(allocator, node_count);
    try g.edges.ensureTotalCapacity(allocator, from.len);

    for (0..node_count) |_| {
        _ = try g.addNode({});
    }

    for (from, to, weight) |f, t, w| {
        _ = try g.addEdge(f, t, w);
    }

    return g;
}

fn extractScores(result: anytype, node_count: usize) ![]f64 {
    const allocator = beam.allocator;
    var scores = try allocator.alloc(f64, node_count);
    errdefer allocator.free(scores);

    for (0..node_count) |i| {
        scores[i] = result.get(@intCast(i));
    }

    return scores;
}

pub fn betweenness_unweighted(node_count: usize, from: []u32, to: []u32) ![]f64 {
    const allocator = beam.allocator;
    var g = ArrayGraph(void, f64).init(allocator);
    defer g.deinit();

    try g.nodes.ensureTotalCapacity(allocator, node_count);
    try g.edges.ensureTotalCapacity(allocator, from.len);

    for (0..node_count) |_| { _ = try g.addNode({}); }
    for (from, to) |f, t| { _ = try g.addEdge(f, t, 1.0); }

    var result = try zog.centrality.betweennessUnweighted(allocator, g);
    defer result.deinit();

    return extractScores(result, node_count);
}

pub fn betweenness_f64(node_count: usize, from: []u32, to: []u32, weight: []f64) ![]f64 {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    var result = try zog.centrality.betweennessF64(beam.allocator, g);
    defer result.deinit();

    return extractScores(result, node_count);
}

pub fn closeness_f64(node_count: usize, from: []u32, to: []u32, weight: []f64) ![]f64 {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    var result = try zog.centrality.closenessF64(beam.allocator, g);
    defer result.deinit();

    return extractScores(result, node_count);
}

pub fn harmonic_centrality_f64(node_count: usize, from: []u32, to: []u32, weight: []f64) ![]f64 {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    var result = try zog.centrality.harmonicCentralityF64(beam.allocator, g);
    defer result.deinit();

    return extractScores(result, node_count);
}

pub fn pagerank(
    node_count: usize,
    from: []u32,
    to: []u32,
    weight: []f64,
    damping: f64,
    max_iterations: usize,
    tolerance: f64,
) ![]f64 {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    var result = try zog.centrality.pagerank(beam.allocator, g, .{
        .damping = damping,
        .max_iterations = max_iterations,
        .tolerance = tolerance,
    });
    defer result.deinit();

    return extractScores(result, node_count);
}

pub fn eigenvector(
    node_count: usize,
    from: []u32,
    to: []u32,
    weight: []f64,
    max_iterations: usize,
    tolerance: f64,
) ![]f64 {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    var result = try zog.centrality.eigenvector(beam.allocator, g, max_iterations, tolerance);
    defer result.deinit();

    return extractScores(result, node_count);
}

pub fn katz(
    node_count: usize,
    from: []u32,
    to: []u32,
    weight: []f64,
    alpha: f64,
    beta: f64,
    max_iterations: usize,
    tolerance: f64,
) ![]f64 {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    var result = try zog.centrality.katz(beam.allocator, g, alpha, beta, max_iterations, tolerance);
    defer result.deinit();

    return extractScores(result, node_count);
}

pub fn alpha_centrality(
    node_count: usize,
    from: []u32,
    to: []u32,
    weight: []f64,
    alpha: f64,
    initial: f64,
    max_iterations: usize,
    tolerance: f64,
) ![]f64 {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    var result = try zog.centrality.alphaCentrality(beam.allocator, g, alpha, initial, max_iterations, tolerance);
    defer result.deinit();

    return extractScores(result, node_count);
}
