// this code is autogenerated, do not check it into to your code repository

// ref lib/zog/traversal.ex:20
const std = @import("std");
const beam = @import("beam");
const zog = @import("zog");

const ArrayGraph = zog.models.ArrayGraph;

fn buildGraph(node_count: usize, from: []u32, to: []u32, weight: []f64) !ArrayGraph(void, f64) {
    const allocator = beam.allocator;
    var g = ArrayGraph(void, f64).init(allocator);
    errdefer g.deinit();

    try g.nodes.ensureTotalCapacity(allocator, node_count);
    try g.edges.ensureTotalCapacity(allocator, from.len);

    for (0..node_count) |_| {
        _ = try g.addNode({});
    }

    for (from, to, weight) |f, t, w| {
        _ = try g.addEdge(f, t, w);
    }

    return g;
}

pub fn nif_is_acyclic(node_count: usize, from: []u32, to: []u32, weight: []f64) !bool {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    return try zog.traversal.isAcyclic(beam.allocator, g);
}

const AlgorithmType = enum { dfs, kahn };

pub fn nif_topological_sort(node_count: usize, from: []u32, to: []u32, weight: []f64, algorithm: beam.term) !beam.term {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    const algo = try beam.get(AlgorithmType, algorithm, .{});
    const order = switch (algo) {
        .dfs => zog.traversal.topologicalSort(beam.allocator, g),
        .kahn => zog.traversal.kahnTopologicalSort(beam.allocator, g),
    } catch |err| {
        if (err == error.Cycle) {
            return beam.make(.{.@"error", .cycle}, .{});
        }
        return err;
    };
    errdefer beam.allocator.free(order);

    const term = beam.make(.{.ok, order}, .{});
    beam.allocator.free(order);
    return term;
}
