// this code is autogenerated, do not check it into to your code repository

// ref lib/zog/mst.ex:16
const std = @import("std");
const beam = @import("beam");
const zog = @import("zog");

const ArrayGraph = zog.models.ArrayGraph;

fn buildGraph(node_count: usize, from: []u32, to: []u32, weight: []f64) !ArrayGraph(void, f64) {
    const allocator = beam.allocator;
    var g = ArrayGraph(void, f64).init(allocator);
    errdefer g.deinit();

    try g.nodes.ensureTotalCapacity(allocator, node_count);
    try g.edges.ensureTotalCapacity(allocator, from.len);

    for (0..node_count) |_| {
        _ = try g.addNode({});
    }

    for (from, to, weight) |f, t, w| {
        _ = try g.addEdge(f, t, w);
    }

    return g;
}

pub fn nif_kruskal(node_count: usize, from: []u32, to: []u32, weight: []f64) !beam.term {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    const res = try zog.mst.kruskal(beam.allocator, g);
    errdefer {
        beam.allocator.free(res.from);
        beam.allocator.free(res.to);
        beam.allocator.free(res.weight);
    }

    const term = beam.make(.{.ok, res.from, res.to, res.weight}, .{});

    beam.allocator.free(res.from);
    beam.allocator.free(res.to);
    beam.allocator.free(res.weight);

    return term;
}
