// this code is autogenerated, do not check it into to your code repository

// ref lib/zog/resource_graph.ex:87
const std = @import("std");
const beam = @import("beam");
const e = @import("erl_nif");
const zog = @import("zog");
const ArrayGraph = zog.models.ArrayGraph;

const GraphResource = union(enum) {
    soa: ArrayGraph(void, f64),
    hash_graph: zog.models.GraphMap(u32, void, f64, .directed, .dual),
};

pub const GraphRes = beam.Resource(GraphResource, @import("root"), .{
    .Callbacks = struct {
        pub fn dtor(ptr: *GraphResource) void {
            switch (ptr.*) {
                .soa => |*g| g.deinit(),
                .hash_graph => |*g| g.deinit(),
            }
        }
    },
});

fn buildGraph(node_count: usize, from: []u32, to: []u32, weight: []f64) !ArrayGraph(void, f64) {
    const allocator = beam.allocator;
    var g = ArrayGraph(void, f64).init(allocator);
    errdefer g.deinit();
    try g.nodes.ensureTotalCapacity(allocator, node_count);
    try g.edges.ensureTotalCapacity(allocator, from.len);
    for (0..node_count) |_| { _ = try g.addNode({}); }
    for (from, to, weight) |f, t, w| { _ = try g.addEdge(f, t, w); }
    return g;
}

fn buildHashGraph(node_count: usize, from: []u32, to: []u32, weight: []f64) !zog.models.GraphMap(u32, void, f64, .directed, .dual) {
    const allocator = beam.allocator;
    var g = zog.models.GraphMap(u32, void, f64, .directed, .dual).init(allocator);
    errdefer g.deinit();
    try g.nodes.ensureTotalCapacity(@intCast(node_count));
    for (0..node_count) |i| {
        try g.addNode(@intCast(i), {});
    }
    for (from, to, weight) |f, t, w| {
        try g.addEdge(f, t, w);
    }
    return g;
}

fn nodeCapacity(res: GraphRes) usize {
    switch (res.unpack()) {
        .soa => |g| return g.nodeCapacity(),
        .hash_graph => |g| return g.nodeCount(),
    }
}

fn nodeCount(res: GraphRes) usize {
    switch (res.unpack()) {
        .soa => |g| return g.nodeCount(),
        .hash_graph => |g| return g.nodeCount(),
    }
}

fn edgeCount(res: GraphRes) usize {
    switch (res.unpack()) {
        .soa => |g| return g.edgeCount(),
        .hash_graph => |g| return g.edgeCount(),
    }
}

fn extractScores(result: anytype, node_count: usize) ![]f64 {
    const allocator = beam.allocator;
    var scores = try allocator.alloc(f64, node_count);
    errdefer allocator.free(scores);
    for (0..node_count) |i| {
        scores[i] = result.get(@intCast(i));
    }
    return scores;
}

fn extractAssignments(result: anytype, node_count: usize) ![]usize {
    const allocator = beam.allocator;
    var assignments = try allocator.alloc(usize, node_count);
    errdefer allocator.free(assignments);
    for (0..node_count) |i| {
        assignments[i] = result.assignments.get(@intCast(i)) orelse 0;
    }
    return assignments;
}

const BackendType = enum { soa, hash_graph };

pub fn new(node_count: usize, from: []u32, to: []u32, weight: []f64, backend: beam.term) !GraphRes {
    const b = try beam.get(BackendType, backend, .{});
    switch (b) {
        .soa => {
            const g = try buildGraph(node_count, from, to, weight);
            return GraphRes.create(.{ .soa = g }, .{ .released = false });
        },
        .hash_graph => {
            const g = try buildHashGraph(node_count, from, to, weight);
            return GraphRes.create(.{ .hash_graph = g }, .{ .released = false });
        }
    }
}

pub fn nif_destroy(res: GraphRes) void {
    res.release();
}

pub fn nif_betweenness_unweighted(res: GraphRes) ![]f64 {
    const allocator = beam.allocator;
    const result = switch (res.unpack()) {
        .soa => |g| try zog.centrality.betweennessUnweighted(allocator, g),
        .hash_graph => |g| try zog.centrality.betweennessUnweighted(allocator, g),
    };
    var mutable_result = result;
    defer mutable_result.deinit();
    return extractScores(mutable_result, nodeCapacity(res));
}

pub fn nif_betweenness_f64(res: GraphRes) ![]f64 {
    const allocator = beam.allocator;
    const result = switch (res.unpack()) {
        .soa => |g| try zog.centrality.betweennessF64(allocator, g),
        .hash_graph => |g| try zog.centrality.betweennessF64(allocator, g),
    };
    var mutable_result = result;
    defer mutable_result.deinit();
    return extractScores(mutable_result, nodeCapacity(res));
}

pub fn nif_closeness_f64(res: GraphRes) ![]f64 {
    const allocator = beam.allocator;
    const result = switch (res.unpack()) {
        .soa => |g| try zog.centrality.closenessF64(allocator, g),
        .hash_graph => |g| try zog.centrality.closenessF64(allocator, g),
    };
    var mutable_result = result;
    defer mutable_result.deinit();
    return extractScores(mutable_result, nodeCapacity(res));
}

pub fn nif_harmonic_centrality_f64(res: GraphRes) ![]f64 {
    const allocator = beam.allocator;
    const result = switch (res.unpack()) {
        .soa => |g| try zog.centrality.harmonicCentralityF64(allocator, g),
        .hash_graph => |g| try zog.centrality.harmonicCentralityF64(allocator, g),
    };
    var mutable_result = result;
    defer mutable_result.deinit();
    return extractScores(mutable_result, nodeCapacity(res));
}

pub fn pagerank(res: GraphRes, damping: f64, max_iterations: usize, tolerance: f64) ![]f64 {
    const allocator = beam.allocator;
    const opts: zog.centrality.PageRankOptions = .{
        .damping = damping,
        .max_iterations = max_iterations,
        .tolerance = tolerance,
    };
    const result = switch (res.unpack()) {
        .soa => |g| try zog.centrality.pagerank(allocator, g, opts),
        .hash_graph => |g| try zog.centrality.pagerank(allocator, g, opts),
    };
    var mutable_result = result;
    defer mutable_result.deinit();
    return extractScores(mutable_result, nodeCapacity(res));
}

pub fn eigenvector(res: GraphRes, max_iterations: usize, tolerance: f64) ![]f64 {
    const allocator = beam.allocator;
    const result = switch (res.unpack()) {
        .soa => |g| try zog.centrality.eigenvector(allocator, g, max_iterations, tolerance),
        .hash_graph => |g| try zog.centrality.eigenvector(allocator, g, max_iterations, tolerance),
    };
    var mutable_result = result;
    defer mutable_result.deinit();
    return extractScores(mutable_result, nodeCapacity(res));
}

pub fn katz(res: GraphRes, alpha: f64, beta: f64, max_iterations: usize, tolerance: f64) ![]f64 {
    const allocator = beam.allocator;
    const result = switch (res.unpack()) {
        .soa => |g| try zog.centrality.katz(allocator, g, alpha, beta, max_iterations, tolerance),
        .hash_graph => |g| try zog.centrality.katz(allocator, g, alpha, beta, max_iterations, tolerance),
    };
    var mutable_result = result;
    defer mutable_result.deinit();
    return extractScores(mutable_result, nodeCapacity(res));
}

pub fn alpha_centrality(res: GraphRes, alpha: f64, initial: f64, max_iterations: usize, tolerance: f64) ![]f64 {
    const allocator = beam.allocator;
    const result = switch (res.unpack()) {
        .soa => |g| try zog.centrality.alphaCentrality(allocator, g, alpha, initial, max_iterations, tolerance),
        .hash_graph => |g| try zog.centrality.alphaCentrality(allocator, g, alpha, initial, max_iterations, tolerance),
    };
    var mutable_result = result;
    defer mutable_result.deinit();
    return extractScores(mutable_result, nodeCapacity(res));
}

pub fn louvain(res: GraphRes, min_modularity_gain: f64, max_iterations: usize, seed: u64) ![]usize {
    const allocator = beam.allocator;
    const opts: zog.community.louvain.LouvainOptions = .{
        .min_modularity_gain = min_modularity_gain,
        .max_iterations = max_iterations,
        .seed = seed,
    };
    const result = switch (res.unpack()) {
        .soa => |g| try zog.community.louvain.detectWeightedWithOptions(allocator, g, opts, zog.utils.identityF64),
        .hash_graph => |g| try zog.community.louvain.detectWeightedWithOptions(allocator, g, opts, zog.utils.identityF64),
    };
    var mutable_result = result;
    defer mutable_result.deinit();
    return extractAssignments(mutable_result, nodeCapacity(res));
}

pub fn leiden(
    res: GraphRes,
    min_modularity_gain: f64,
    max_iterations: usize,
    seed: u64,
    theta: f64,
) ![]usize {
    const allocator = beam.allocator;
    const opts: zog.community.leiden.LeidenOptions = .{
        .min_modularity_gain = min_modularity_gain,
        .max_iterations = max_iterations,
        .seed = seed,
        .theta = theta,
    };
    const result = switch (res.unpack()) {
        .soa => |g| try zog.community.leiden.detectWeightedWithOptions(allocator, g, opts, zog.utils.identityF64),
        .hash_graph => |g| try zog.community.leiden.detectWeightedWithOptions(allocator, g, opts, zog.utils.identityF64),
    };
    var mutable_result = result;
    defer mutable_result.deinit();
    return extractAssignments(mutable_result, nodeCapacity(res));
}

pub fn leiden_hierarchical(
    res: GraphRes,
    min_modularity_gain: f64,
    max_iterations: usize,
    seed: u64,
    theta: f64,
) ![][]usize {
    const allocator = beam.allocator;
    const opts: zog.community.leiden.LeidenOptions = .{
        .min_modularity_gain = min_modularity_gain,
        .max_iterations = max_iterations,
        .seed = seed,
        .theta = theta,
    };
    const result = switch (res.unpack()) {
        .soa => |g| try zog.community.leiden.detectHierarchicalWeightedWithOptions(allocator, g, opts, zog.utils.identityF64),
        .hash_graph => |g| try zog.community.leiden.detectHierarchicalWeightedWithOptions(allocator, g, opts, zog.utils.identityF64),
    };
    var mutable_result = result;
    defer mutable_result.deinit();

    const node_count = nodeCapacity(res);
    const outer = try allocator.alloc([]usize, mutable_result.levels.len);
    errdefer allocator.free(outer);

    for (mutable_result.levels, 0..) |level, i| {
        const level_copy = try allocator.alloc(usize, node_count);
        errdefer allocator.free(level_copy);
        @memcpy(level_copy, level);
        outer[i] = level_copy;
    }

    return outer;
}

pub fn label_propagation(res: GraphRes, max_iterations: usize, seed: u64) ![]usize {
    const allocator = beam.allocator;
    const opts: zog.community.label_propagation.LabelPropagationOptions = .{
        .max_iterations = max_iterations,
        .seed = seed,
    };
    const result = switch (res.unpack()) {
        .soa => |g| try zog.community.label_propagation.labelPropagation(allocator, g, opts),
        .hash_graph => |g| try zog.community.label_propagation.labelPropagation(allocator, g, opts),
    };
    var mutable_result = result;
    defer mutable_result.deinit();
    return extractAssignments(mutable_result, nodeCapacity(res));
}

pub fn modularity_f64(res: GraphRes, assignments: []usize) !f64 {
    const allocator = beam.allocator;
    var map = std.AutoHashMap(u32, usize).init(allocator);
    defer map.deinit();
    for (assignments, 0..) |comm, i| {
        try map.put(@intCast(i), comm);
    }
    return switch (res.unpack()) {
        .soa => |g| try zog.community.metrics.modularity(allocator, g, map, zog.utils.identityF64),
        .hash_graph => |g| try zog.community.metrics.modularity(allocator, g, map, zog.utils.identityF64),
    };
}

fn extractMatrix(result: anytype, node_count: usize) !beam.term {
    var matrix = try beam.allocator.alloc(f64, node_count * node_count);
    defer beam.allocator.free(matrix);
    for (0..node_count) |i| {
        for (0..node_count) |j| {
            matrix[i * node_count + j] = result.get(@intCast(i), @intCast(j)) orelse std.math.inf(f64);
        }
    }
    return beam.make(.{.ok, matrix}, .{});
}

pub fn nif_floyd_warshall(res: GraphRes) !beam.term {
    const allocator = beam.allocator;
    const node_count = nodeCapacity(res);
    const result_or_err = switch (res.unpack()) {
        .soa => |g| zog.pathfinding.floydWarshall(allocator, g),
        .hash_graph => |g| zog.pathfinding.floydWarshall(allocator, g),
    };
    var result = result_or_err catch |err| {
        if (err == error.NegativeCycle) {
            return beam.make(.{.@"error", .negative_cycle}, .{});
        }
        return err;
    };
    defer result.deinit();
    return extractMatrix(result, node_count);
}

pub fn nif_johnsons(res: GraphRes) !beam.term {
    const allocator = beam.allocator;
    const node_count = nodeCapacity(res);
    const result_or_err = switch (res.unpack()) {
        .soa => |g| zog.pathfinding.johnsonsGeneric(allocator, g, f64, 0.0, zog.utils.addF64, zog.utils.subF64, zog.utils.compareF64),
        .hash_graph => |g| zog.pathfinding.johnsonsGeneric(allocator, g, f64, 0.0, zog.utils.addF64, zog.utils.subF64, zog.utils.compareF64),
    };
    var result = result_or_err catch |err| {
        if (err == error.NegativeCycle) {
            return beam.make(.{.@"error", .negative_cycle}, .{});
        }
        return err;
    };
    defer result.deinit();
    return extractMatrix(result, node_count);
}

pub fn nif_dijkstra(res: GraphRes, start_node: u32, goal_node: u32) !beam.term {
    const allocator = beam.allocator;
    const opt_res_or_err = switch (res.unpack()) {
        .soa => |g| zog.pathfinding.dijkstra(allocator, g, start_node, goal_node),
        .hash_graph => |g| zog.pathfinding.dijkstra(allocator, g, start_node, goal_node),
    };
    const opt_res = opt_res_or_err catch |err| {
        return err;
    };

    if (opt_res) |res_val| {
        var path_res = res_val;
        defer path_res.deinit(allocator);

        const path_slice = try allocator.alloc(u32, path_res.path.items.len);
        @memcpy(path_slice, path_res.path.items);

        return beam.make(.{.ok, .{path_slice, path_res.weight}}, .{});
    } else {
        return beam.make(.{.@"error", .no_path}, .{});
    }
}

pub fn nif_astar(
    res: GraphRes,
    start_node: u32,
    goal_node: u32,
    x_coords: []f64,
    y_coords: []f64,
    heuristic: beam.term,
) !beam.term {
    const allocator = beam.allocator;
    const HeuristicType = zog.pathfinding.HeuristicType;
    const h_type = try beam.get(HeuristicType, heuristic, .{});

    const opt_res_or_err = switch (res.unpack()) {
        .soa => |g| zog.pathfinding.astar(allocator, g, start_node, goal_node, x_coords, y_coords, h_type),
        .hash_graph => |g| zog.pathfinding.astar(allocator, g, start_node, goal_node, x_coords, y_coords, h_type),
    };
    const opt_res = opt_res_or_err catch |err| {
        return err;
    };

    if (opt_res) |res_val| {
        var path_res = res_val;
        defer path_res.deinit(allocator);

        const path_slice = try allocator.alloc(u32, path_res.path.items.len);
        @memcpy(path_slice, path_res.path.items);

        return beam.make(.{.ok, .{path_slice, path_res.weight}}, .{});
    } else {
        return beam.make(.{.@"error", .no_path}, .{});
    }
}

pub fn nif_is_reachable(res: GraphRes, start_node: u32, goal_node: u32) !beam.term {
    const allocator = beam.allocator;
    const reachable = switch (res.unpack()) {
        .soa => |g| try zog.pathfinding.isReachable(allocator, g, start_node, goal_node),
        .hash_graph => |g| try zog.pathfinding.isReachable(allocator, g, start_node, goal_node),
    };
    return beam.make(reachable, .{});
}

pub fn nif_density(res: GraphRes) !f64 {
    const n = nodeCount(res);
    if (n <= 1) return 0.0;
    const possible_edges = @as(f64, @floatFromInt(n * (n - 1)));
    return @as(f64, @floatFromInt(edgeCount(res))) / possible_edges;
}

pub fn nif_triangle_count(res: GraphRes) !usize {
    const allocator = beam.allocator;
    return switch (res.unpack()) {
        .soa => |g| try zog.community.metrics.countTriangles(allocator, g),
        .hash_graph => |g| try zog.community.metrics.countTriangles(allocator, g),
    };
}

pub fn nif_average_clustering_coefficient(res: GraphRes) !f64 {
    const allocator = beam.allocator;
    return switch (res.unpack()) {
        .soa => |g| try zog.community.metrics.averageClusteringCoefficient(allocator, g),
        .hash_graph => |g| try zog.community.metrics.averageClusteringCoefficient(allocator, g),
    };
}

pub fn nif_local_clustering_coefficient(res: GraphRes) ![]f64 {
    const allocator = beam.allocator;
    const node_count = nodeCapacity(res);
    var scores = try allocator.alloc(f64, node_count);
    errdefer allocator.free(scores);
    switch (res.unpack()) {
        .soa => |g| {
            for (0..node_count) |i| {
                scores[i] = zog.community.metrics.clusteringCoefficient(allocator, g, @intCast(i)) catch 0.0;
            }
        },
        .hash_graph => |g| {
            for (0..node_count) |i| {
                scores[i] = zog.community.metrics.clusteringCoefficient(allocator, g, @intCast(i)) catch 0.0;
            }
        },
    }
    return scores;
}

pub fn nif_assortativity(res: GraphRes) !f64 {
    const allocator = beam.allocator;
    return switch (res.unpack()) {
        .soa => |g| try zog.metrics.assortativity(allocator, g),
        .hash_graph => |g| try zog.metrics.assortativity(allocator, g),
    };
}

pub fn nif_anf(res: GraphRes, max_steps: usize, m: usize) !beam.term {
    const allocator = beam.allocator;
    const result = switch (res.unpack()) {
        .soa => |g| try zog.metrics.anf(allocator, g, max_steps, m),
        .hash_graph => |g| try zog.metrics.anf(allocator, g, max_steps, m),
    };
    errdefer allocator.free(result.neighborhood_sizes);

    const term = beam.make(.{.ok, result.neighborhood_sizes, result.effective_diameter}, .{});
    allocator.free(result.neighborhood_sizes);
    return term;
}

pub fn nif_core_numbers(res: GraphRes) ![]u32 {
    const allocator = beam.allocator;
    return switch (res.unpack()) {
        .soa => |g| try zog.connectivity.coreNumbers(allocator, g),
        .hash_graph => |g| try zog.connectivity.coreNumbers(allocator, g),
    };
}

pub fn nif_strongly_connected_components(res: GraphRes) ![]u32 {
    const allocator = beam.allocator;
    return switch (res.unpack()) {
        .soa => |g| try zog.connectivity.stronglyConnectedComponents(allocator, g),
        .hash_graph => |g| try zog.connectivity.stronglyConnectedComponents(allocator, g),
    };
}

pub fn nif_weakly_connected_components(res: GraphRes) ![]u32 {
    const allocator = beam.allocator;
    return switch (res.unpack()) {
        .soa => |g| try zog.connectivity.weaklyConnectedComponents(allocator, g),
        .hash_graph => |g| try zog.connectivity.weaklyConnectedComponents(allocator, g),
    };
}

pub fn nif_kruskal(res: GraphRes) !beam.term {
    const allocator = beam.allocator;
    const result = switch (res.unpack()) {
        .soa => |g| try zog.mst.kruskal(allocator, g),
        .hash_graph => |g| try zog.mst.kruskal(allocator, g),
    };
    errdefer {
        allocator.free(result.from);
        allocator.free(result.to);
        allocator.free(result.weight);
    }

    const term = beam.make(.{.ok, result.from, result.to, result.weight}, .{});

    allocator.free(result.from);
    allocator.free(result.to);
    allocator.free(result.weight);

    return term;
}

pub fn nif_bellman_ford(res: GraphRes, start_node: u32, goal_node: u32) !beam.term {
    const allocator = beam.allocator;
    const opt_res_or_err = switch (res.unpack()) {
        .soa => |g| zog.pathfinding.bellmanFord(allocator, g, start_node, goal_node),
        .hash_graph => |g| zog.pathfinding.bellmanFord(allocator, g, start_node, goal_node),
    };
    const opt_res = opt_res_or_err catch |err| {
        if (err == error.NegativeCycle) {
            return beam.make(.{.@"error", .negative_cycle}, .{});
        }
        return err;
    };

    if (opt_res) |p_res| {
        var path_res = p_res;
        defer path_res.deinit(allocator);

        const path_slice = try allocator.alloc(u32, path_res.path.items.len);
        @memcpy(path_slice, path_res.path.items);

        return beam.make(.{.ok, .{path_slice, path_res.weight}}, .{});
    } else {
        return beam.make(.{.@"error", .no_path}, .{});
    }
}

pub fn nif_analyze_connectivity(res: GraphRes) !beam.term {
    const allocator = beam.allocator;
    const res_conn = switch (res.unpack()) {
        .soa => |g| try zog.connectivity.analyzeConnectivity(allocator, g),
        .hash_graph => |g| try zog.connectivity.analyzeConnectivity(allocator, g),
    };
    errdefer {
        allocator.free(res_conn.bridges);
        allocator.free(res_conn.articulation_points);
    }

    const term = beam.make(.{.ok, res_conn.bridges, res_conn.articulation_points}, .{});

    allocator.free(res_conn.bridges);
    allocator.free(res_conn.articulation_points);

    return term;
}

const FlowNifResult = struct {
    max_flow: f64,
    residual_from: []u32,
    residual_to: []u32,
    residual_cap: []f64,
    source_side: []u32,
    sink_side: []u32,
};

fn toFlowNifResult(
    allocator: std.mem.Allocator,
    max_flow: f64,
    residual: anytype,
    source_side: []u32,
    sink_side: []u32,
) !FlowNifResult {
    const res_count = residual.count();
    var res_from = try allocator.alloc(u32, res_count);
    errdefer allocator.free(res_from);
    var res_to = try allocator.alloc(u32, res_count);
    errdefer allocator.free(res_to);
    var res_cap = try allocator.alloc(f64, res_count);
    errdefer allocator.free(res_cap);

    var it = residual.iterator();
    var idx: usize = 0;
    while (it.next()) |entry| {
        res_from[idx] = entry.key_ptr.from;
        res_to[idx] = entry.key_ptr.to;
        res_cap[idx] = entry.value_ptr.*;
        idx += 1;
    }

    const ss = try allocator.alloc(u32, source_side.len);
    errdefer allocator.free(ss);
    @memcpy(ss, source_side);

    const sk = try allocator.alloc(u32, sink_side.len);
    errdefer allocator.free(sk);
    @memcpy(sk, sink_side);

    return .{
        .max_flow = max_flow,
        .residual_from = res_from,
        .residual_to = res_to,
        .residual_cap = res_cap,
        .source_side = ss,
        .sink_side = sk,
    };
}

pub fn nif_max_flow(res: GraphRes, source: u32, sink: u32) !beam.term {
    const allocator = beam.allocator;
    const result = switch (res.unpack()) {
        .soa => |g| try zog.flow.max_flow.edmondsKarpF64(allocator, g, source, sink),
        .hash_graph => |g| try zog.flow.max_flow.edmondsKarpF64(allocator, g, source, sink),
    };
    var mutable_result = result;
    defer mutable_result.deinit(allocator);

    var cut = try zog.flow.max_flow.minCut(allocator, mutable_result, f64, 0.0, zog.utils.compareF64);
    defer cut.deinit(allocator);

    const flow_res = try toFlowNifResult(allocator, mutable_result.max_flow, mutable_result.residual, cut.source_side, cut.sink_side);
    defer {
        allocator.free(flow_res.residual_from);
        allocator.free(flow_res.residual_to);
        allocator.free(flow_res.residual_cap);
        allocator.free(flow_res.source_side);
        allocator.free(flow_res.sink_side);
    }

    return beam.make(.{
        .max_flow = flow_res.max_flow,
        .residual_from = flow_res.residual_from,
        .residual_to = flow_res.residual_to,
        .residual_cap = flow_res.residual_cap,
        .source_side = flow_res.source_side,
        .sink_side = flow_res.sink_side,
    }, .{});
}

pub fn nif_push_relabel(res: GraphRes, source: u32, sink: u32) !beam.term {
    const allocator = beam.allocator;
    const result = switch (res.unpack()) {
        .soa => |g| try zog.flow.max_flow.pushRelabelF64(allocator, g, source, sink),
        .hash_graph => |g| try zog.flow.max_flow.pushRelabelF64(allocator, g, source, sink),
    };
    var mutable_result = result;
    defer mutable_result.deinit(allocator);

    var cut = try zog.flow.max_flow.minCut(allocator, mutable_result, f64, 0.0, zog.utils.compareF64);
    defer cut.deinit(allocator);

    const flow_res = try toFlowNifResult(allocator, mutable_result.max_flow, mutable_result.residual, cut.source_side, cut.sink_side);
    defer {
        allocator.free(flow_res.residual_from);
        allocator.free(flow_res.residual_to);
        allocator.free(flow_res.residual_cap);
        allocator.free(flow_res.source_side);
        allocator.free(flow_res.sink_side);
    }

    return beam.make(.{
        .max_flow = flow_res.max_flow,
        .residual_from = flow_res.residual_from,
        .residual_to = flow_res.residual_to,
        .residual_cap = flow_res.residual_cap,
        .source_side = flow_res.source_side,
        .sink_side = flow_res.sink_side,
    }, .{});
}

pub fn nif_global_min_cut(res: GraphRes) !beam.term {
    const allocator = beam.allocator;
    const result = switch (res.unpack()) {
        .soa => |g| try zog.flow.min_cut.globalMinCutF64(allocator, g),
        .hash_graph => |g| try zog.flow.min_cut.globalMinCutF64(allocator, g),
    };
    defer {
        allocator.free(result.group_a);
        allocator.free(result.group_b);
    }

    return beam.make(.{
        .cut_value = result.weight,
        .source_side = result.group_a,
        .sink_side = result.group_b,
    }, .{});
}

fn getOrInsertNodeId(
    arena: std.mem.Allocator,
    label_to_id: *std.StringHashMap(u32),
    labels_list: *std.ArrayList([]const u8),
    next_id: *u32,
    label: []const u8,
) !u32 {
    if (label_to_id.get(label)) |id| {
        return id;
    }
    const id = next_id.*;
    const key_copy = try arena.dupe(u8, label);
    try label_to_id.put(key_copy, id);
    try labels_list.append(arena, key_copy);
    next_id.* += 1;
    return id;
}

const ParsedEdge = struct {
    from: u32,
    to: u32,
    weight: f64,
};

pub fn nif_read_edgelist(file_path: []const u8, is_directed: bool, backend: beam.term, integer_labels: bool) !beam.term {
    const b = try beam.get(BackendType, backend, .{});
    const io = beam.io.get(beam.allocator);

    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const arena_allocator = arena.allocator();

    var file = try std.Io.Dir.cwd().openFile(io, file_path, .{});
    defer file.close(io);

    var label_to_id = std.StringHashMap(u32).init(arena_allocator);
    var labels_list: std.ArrayList([]const u8) = .empty;
    defer labels_list.deinit(arena_allocator);
    var next_id: u32 = 0;

    var edges: std.ArrayList(ParsedEdge) = .empty;
    defer edges.deinit(arena_allocator);

    var read_buffer: [4096]u8 = undefined;
    var file_reader = file.reader(io, &read_buffer);
    const reader = &file_reader.interface;

    while (true) {
        const line = reader.takeDelimiterExclusive('\n') catch |err| {
            if (err == error.EndOfStream) break;
            return err;
        };
        reader.toss(1);

        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (trimmed.len == 0 or trimmed[0] == '#') continue;

        var parts = std.mem.tokenizeAny(u8, trimmed, " \t,");
        const src_lbl = parts.next() orelse continue;
        const dst_lbl = parts.next() orelse continue;
        const opt_weight = parts.next();

        if (std.ascii.eqlIgnoreCase(src_lbl, "source") and std.ascii.eqlIgnoreCase(dst_lbl, "target")) {
            continue;
        }

        const weight = if (opt_weight) |w_str| std.fmt.parseFloat(f64, w_str) catch 1.0 else 1.0;

        var src_id: u32 = 0;
        var dst_id: u32 = 0;

        if (integer_labels) {
            src_id = std.fmt.parseInt(u32, src_lbl, 10) catch continue;
            dst_id = std.fmt.parseInt(u32, dst_lbl, 10) catch continue;
            const max_val = @max(src_id, dst_id);
            if (max_val >= next_id) {
                next_id = max_val + 1;
            }
        } else {
            src_id = try getOrInsertNodeId(arena_allocator, &label_to_id, &labels_list, &next_id, src_lbl);
            dst_id = try getOrInsertNodeId(arena_allocator, &label_to_id, &labels_list, &next_id, dst_lbl);
        }

        try edges.append(arena_allocator, .{ .from = src_id, .to = dst_id, .weight = weight });
    }

    switch (b) {
        .soa => {
            var g = ArrayGraph(void, f64).init(beam.allocator);
            errdefer g.deinit();
            try g.nodes.ensureTotalCapacity(beam.allocator, next_id);
            for (0..next_id) |_| { _ = try g.addNode({}); }
            for (edges.items) |edge| {
                _ = try g.addEdge(edge.from, edge.to, edge.weight);
                if (!is_directed) {
                    _ = try g.addEdge(edge.to, edge.from, edge.weight);
                }
            }
            const resource = try GraphRes.create(.{ .soa = g }, .{ .released = false });
            if (integer_labels) {
                return beam.make(.{.ok, resource, next_id}, .{});
            } else {
                const labels_slice = try labels_list.toOwnedSlice(arena_allocator);
                return beam.make(.{.ok, resource, labels_slice}, .{});
            }
        },
        .hash_graph => {
            var g = zog.models.GraphMap(u32, void, f64, .directed, .dual).init(beam.allocator);
            errdefer g.deinit();
            try g.nodes.ensureTotalCapacity(@intCast(next_id));
            for (0..next_id) |i| {
                try g.addNode(@intCast(i), {});
            }
            for (edges.items) |edge| {
                try g.addEdge(edge.from, edge.to, edge.weight);
                if (!is_directed) {
                    try g.addEdge(edge.to, edge.from, edge.weight);
                }
            }
            const resource = try GraphRes.create(.{ .hash_graph = g }, .{ .released = false });
            if (integer_labels) {
                return beam.make(.{.ok, resource, next_id}, .{});
            } else {
                const labels_slice = try labels_list.toOwnedSlice(arena_allocator);
                return beam.make(.{.ok, resource, labels_slice}, .{});
            }
        }
    }
}

pub fn nif_read_adjlist(file_path: []const u8, is_directed: bool, backend: beam.term, integer_labels: bool) !beam.term {
    const b = try beam.get(BackendType, backend, .{});
    const io = beam.io.get(beam.allocator);

    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const arena_allocator = arena.allocator();

    var file = try std.Io.Dir.cwd().openFile(io, file_path, .{});
    defer file.close(io);

    var label_to_id = std.StringHashMap(u32).init(arena_allocator);
    var labels_list: std.ArrayList([]const u8) = .empty;
    defer labels_list.deinit(arena_allocator);
    var next_id: u32 = 0;

    var edges: std.ArrayList(ParsedEdge) = .empty;
    defer edges.deinit(arena_allocator);

    var read_buffer: [4096]u8 = undefined;
    var file_reader = file.reader(io, &read_buffer);
    const reader = &file_reader.interface;

    while (true) {
        const line = reader.takeDelimiterExclusive('\n') catch |err| {
            if (err == error.EndOfStream) break;
            return err;
        };
        reader.toss(1);

        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (trimmed.len == 0 or trimmed[0] == '#') continue;

        const colon_idx = std.mem.indexOf(u8, trimmed, ":") orelse continue;
        const src_lbl = std.mem.trim(u8, trimmed[0..colon_idx], " \t");
        const neighbors_part = trimmed[colon_idx + 1 ..];

        var src_id: u32 = 0;
        if (integer_labels) {
            src_id = std.fmt.parseInt(u32, src_lbl, 10) catch continue;
            if (src_id >= next_id) {
                next_id = src_id + 1;
            }
        } else {
            src_id = try getOrInsertNodeId(arena_allocator, &label_to_id, &labels_list, &next_id, src_lbl);
        }

        var neighbors_it = std.mem.tokenizeAny(u8, neighbors_part, " \t");
        while (neighbors_it.next()) |neighbor_token| {
            var neighbor_parts = std.mem.splitScalar(u8, neighbor_token, ',');
            const dst_lbl = neighbor_parts.first();
            const opt_w = neighbor_parts.next();
            const weight = if (opt_w) |w_str| std.fmt.parseFloat(f64, w_str) catch 1.0 else 1.0;

            var dst_id: u32 = 0;
            if (integer_labels) {
                dst_id = std.fmt.parseInt(u32, dst_lbl, 10) catch continue;
                if (dst_id >= next_id) {
                    next_id = dst_id + 1;
                }
            } else {
                dst_id = try getOrInsertNodeId(arena_allocator, &label_to_id, &labels_list, &next_id, dst_lbl);
            }
            try edges.append(arena_allocator, .{ .from = src_id, .to = dst_id, .weight = weight });
        }
    }

    switch (b) {
        .soa => {
            var g = ArrayGraph(void, f64).init(beam.allocator);
            errdefer g.deinit();
            try g.nodes.ensureTotalCapacity(beam.allocator, next_id);
            for (0..next_id) |_| { _ = try g.addNode({}); }
            for (edges.items) |edge| {
                _ = try g.addEdge(edge.from, edge.to, edge.weight);
                if (!is_directed) {
                    _ = try g.addEdge(edge.to, edge.from, edge.weight);
                }
            }
            const resource = try GraphRes.create(.{ .soa = g }, .{ .released = false });
            if (integer_labels) {
                return beam.make(.{.ok, resource, next_id}, .{});
            } else {
                const labels_slice = try labels_list.toOwnedSlice(arena_allocator);
                return beam.make(.{.ok, resource, labels_slice}, .{});
            }
        },
        .hash_graph => {
            var g = zog.models.GraphMap(u32, void, f64, .directed, .dual).init(beam.allocator);
            errdefer g.deinit();
            try g.nodes.ensureTotalCapacity(@intCast(next_id));
            for (0..next_id) |i| {
                try g.addNode(@intCast(i), {});
            }
            for (edges.items) |edge| {
                try g.addEdge(edge.from, edge.to, edge.weight);
                if (!is_directed) {
                    try g.addEdge(edge.to, edge.from, edge.weight);
                }
            }
            const resource = try GraphRes.create(.{ .hash_graph = g }, .{ .released = false });
            if (integer_labels) {
                return beam.make(.{.ok, resource, next_id}, .{});
            } else {
                const labels_slice = try labels_list.toOwnedSlice(arena_allocator);
                return beam.make(.{.ok, resource, labels_slice}, .{});
            }
        }
    }
}

pub fn nif_read_tgf(file_path: []const u8, is_directed: bool, backend: beam.term, integer_labels: bool) !beam.term {
    const b = try beam.get(BackendType, backend, .{});
    const io = beam.io.get(beam.allocator);

    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const arena_allocator = arena.allocator();

    var file = try std.Io.Dir.cwd().openFile(io, file_path, .{});
    defer file.close(io);

    var label_to_id = std.StringHashMap(u32).init(arena_allocator);
    var labels_list: std.ArrayList([]const u8) = .empty;
    defer labels_list.deinit(arena_allocator);
    var next_id: u32 = 0;

    var edges: std.ArrayList(ParsedEdge) = .empty;
    defer edges.deinit(arena_allocator);

    var parsing_edges = false;
    var read_buffer: [4096]u8 = undefined;
    var file_reader = file.reader(io, &read_buffer);
    const reader = &file_reader.interface;

    while (true) {
        const line = reader.takeDelimiterExclusive('\n') catch |err| {
            if (err == error.EndOfStream) break;
            return err;
        };
        reader.toss(1);

        const trimmed = std.mem.trim(u8, line, " \t\r");
        if (trimmed.len == 0) continue;

        if (std.mem.eql(u8, trimmed, "#")) {
            parsing_edges = true;
            continue;
        }

        if (!parsing_edges) {
            var parts = std.mem.tokenizeAny(u8, trimmed, " \t");
            const node_lbl = parts.next() orelse continue;
            if (integer_labels) {
                const val = std.fmt.parseInt(u32, node_lbl, 10) catch continue;
                if (val >= next_id) {
                    next_id = val + 1;
                }
            } else {
                _ = try getOrInsertNodeId(arena_allocator, &label_to_id, &labels_list, &next_id, node_lbl);
            }
        } else {
            var parts = std.mem.tokenizeAny(u8, trimmed, " \t");
            const src_lbl = parts.next() orelse continue;
            const dst_lbl = parts.next() orelse continue;
            const opt_w = parts.next();
            const weight = if (opt_w) |w_str| std.fmt.parseFloat(f64, w_str) catch 1.0 else 1.0;

            var src_id: u32 = 0;
            var dst_id: u32 = 0;
            if (integer_labels) {
                src_id = std.fmt.parseInt(u32, src_lbl, 10) catch continue;
                dst_id = std.fmt.parseInt(u32, dst_lbl, 10) catch continue;
                const max_val = @max(src_id, dst_id);
                if (max_val >= next_id) {
                    next_id = max_val + 1;
                }
            } else {
                src_id = try getOrInsertNodeId(arena_allocator, &label_to_id, &labels_list, &next_id, src_lbl);
                dst_id = try getOrInsertNodeId(arena_allocator, &label_to_id, &labels_list, &next_id, dst_lbl);
            }

            try edges.append(arena_allocator, .{ .from = src_id, .to = dst_id, .weight = weight });
        }
    }

    switch (b) {
        .soa => {
            var g = ArrayGraph(void, f64).init(beam.allocator);
            errdefer g.deinit();
            try g.nodes.ensureTotalCapacity(beam.allocator, next_id);
            for (0..next_id) |_| { _ = try g.addNode({}); }
            for (edges.items) |edge| {
                _ = try g.addEdge(edge.from, edge.to, edge.weight);
                if (!is_directed) {
                    _ = try g.addEdge(edge.to, edge.from, edge.weight);
                }
            }
            const resource = try GraphRes.create(.{ .soa = g }, .{ .released = false });
            if (integer_labels) {
                return beam.make(.{.ok, resource, next_id}, .{});
            } else {
                const labels_slice = try labels_list.toOwnedSlice(arena_allocator);
                return beam.make(.{.ok, resource, labels_slice}, .{});
            }
        },
        .hash_graph => {
            var g = zog.models.GraphMap(u32, void, f64, .directed, .dual).init(beam.allocator);
            errdefer g.deinit();
            try g.nodes.ensureTotalCapacity(@intCast(next_id));
            for (0..next_id) |i| {
                try g.addNode(@intCast(i), {});
            }
            for (edges.items) |edge| {
                try g.addEdge(edge.from, edge.to, edge.weight);
                if (!is_directed) {
                    try g.addEdge(edge.to, edge.from, edge.weight);
                }
            }
            const resource = try GraphRes.create(.{ .hash_graph = g }, .{ .released = false });
            if (integer_labels) {
                return beam.make(.{.ok, resource, next_id}, .{});
            } else {
                const labels_slice = try labels_list.toOwnedSlice(arena_allocator);
                return beam.make(.{.ok, resource, labels_slice}, .{});
            }
        }
    }
}
