// this code is autogenerated, do not check it into to your code repository

// ref lib/zog/metrics.ex:20
const std = @import("std");
const beam = @import("beam");
const zog = @import("zog");

const ArrayGraph = zog.models.ArrayGraph;

fn buildGraph(node_count: usize, from: []u32, to: []u32, weight: []f64) !ArrayGraph(void, f64) {
    const allocator = beam.allocator;
    var g = ArrayGraph(void, f64).init(allocator);
    errdefer g.deinit();

    try g.nodes.ensureTotalCapacity(allocator, node_count);
    try g.edges.ensureTotalCapacity(allocator, from.len);

    for (0..node_count) |_| {
        _ = try g.addNode({});
    }

    for (from, to, weight) |f, t, w| {
        _ = try g.addEdge(f, t, w);
    }

    return g;
}

pub fn density(node_count: usize, from: []u32, to: []u32, weight: []f64) !f64 {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    return zog.community.metrics.density(g);
}

pub fn triangle_count(node_count: usize, from: []u32, to: []u32, weight: []f64) !usize {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    return try zog.community.metrics.countTriangles(beam.allocator, g);
}

pub fn average_clustering_coefficient(node_count: usize, from: []u32, to: []u32, weight: []f64) !f64 {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    return try zog.community.metrics.averageClusteringCoefficient(beam.allocator, g);
}

pub fn local_clustering_coefficient(node_count: usize, from: []u32, to: []u32, weight: []f64) ![]f64 {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    var scores = try beam.allocator.alloc(f64, node_count);
    errdefer beam.allocator.free(scores);

    for (0..node_count) |i| {
        scores[i] = try zog.community.metrics.clusteringCoefficient(beam.allocator, g, @intCast(i));
    }

    return scores;
}

pub fn assortativity(node_count: usize, from: []u32, to: []u32, weight: []f64) !f64 {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    return try zog.metrics.assortativity(beam.allocator, g);
}

pub fn nif_anf(node_count: usize, from: []u32, to: []u32, weight: []f64, max_steps: usize, m: usize) !beam.term {
    var g = try buildGraph(node_count, from, to, weight);
    defer g.deinit();

    const res = try zog.metrics.anf(beam.allocator, g, max_steps, m);
    errdefer beam.allocator.free(res.neighborhood_sizes);

    const term = beam.make(.{.ok, res.neighborhood_sizes, res.effective_diameter}, .{});
    beam.allocator.free(res.neighborhood_sizes);
    return term;
}
